### ISSUE TITLE
Theme not displaying properly

### ISSUE THREAD

**Issue by jjblack91** [jacobtomlinson/terminal-piperita#7]
Hello,

I am relatively new to using the terminal themes. I am on a Mac running oS Sierra with the default terminal. I have downloaded the piperita theme, but it is not s=displaying properly. The background appears as a black transparent background, but the text colors are not appearing as expected Any insight into how to fix this would be highly appreciated!

Thanks!

**Comment by jacobtomlinson** [comment]
I have just done a fresh install of the theme on MacOS Sierra and it displays as expected. This was simply by downloading the `.terminal` file from the repo and double clicking it.

Could you please attach a screenshot of your terminal and also of the preferences window for the theme.
